CREATE DATABASE IF NOT EXISTS BD_APLICATIVO_MUSICA;
USE BD_APLICATIVO_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASC DATE NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TIPO_MUSICA VARCHAR(20) NOT NULL,
    DESCRICAO VARCHAR(400) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CAPA BLOB NOT NULL,
    DATA_LANC DATE NOT NULL,
    QTD_MUSICA INTEGER NOT NULL,
    FK_CPF_ARTISTA VARCHAR(15) NOT NULL,
    FOREIGN KEY (FK_CPF_ARTISTA) REFERENCES ARTISTA(CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LETRA VARCHAR(9999),
    CAPA BLOB NOT NULL,
    DURACAO FLOAT NOT NULL,
    DATA_LANC DATE NOT NULL,
    FK_ID_ALBUM INTEGER,
    FOREIGN KEY (FK_ID_ALBUM) REFERENCES ALBUM(ID) ON DELETE CASCADE,
    FK_ID_GENERO INTEGER,
    FOREIGN KEY (FK_ID_GENERO) REFERENCES GENERO(ID) ON DELETE CASCADE
);
    
    