CREATE DATABASE IF NOT EXISTS BD_ENQUETES;
USE BD_ENQUETES;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_CODIGO INTEGER AUTO_INCREMENT,
    USU_DATA_CADASTRO DATE NOT NULL,
    USU_LOGIN VARCHAR(255) NOT NULL UNIQUE,
    USU_AREA_ATUACAO VARCHAR(500),
    USU_PROFISSAO VARCHAR(200),
    USU_AREA_FORMACAO VARCHAR(500),
    USU_DATANASC DATE NOT NULL,
    USU_ESTADO_CIVIL ENUM("SOLTEIRO","CASADO","DIVORCIADO","VIÚVO") NOT NULL,
    USU_ESTADO VARCHAR(2) NOT NULL,
    USU_ESCOLARIDADE ENUM("FUNDAMENTAL","MÉDIO","SUPERIOR") NOT NULL,
    USU_EMAIL VARCHAR (255) UNIQUE NOT NULL,
    USU_SENHA VARCHAR(255) NOT NULL,
    USU_NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY (USU_CODIGO)
);

CREATE TABLE IF NOT EXISTS ENQUETE(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
    ENQ_DATA_FINAL DATE,
    ENQ_DATA_INICIAL DATE NOT NULL,
    ENQ_DESCRICAO VARCHAR(450) NOT NULL,
    ENQ_NOME VARCHAR(200) NOT NULL,
    FK_USU_CODIGO INTEGER,
    PRIMARY KEY(ENQ_CODIGO),
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USUARIO_RESPONDE_ENQUETE(
	URE_CODIGO INTEGER AUTO_INCREMENT,
    URE_DATA DATE NOT NULL,
    FK_USU_CODIGO INTEGER,
    FK_ENQ_CODIGO INTEGER,
    PRIMARY KEY (URE_CODIGO),
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE,
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PERGUNTAS(
	PER_CODIGO INTEGER AUTO_INCREMENT,
    PER_DESCRICAO VARCHAR(255) NOT NULL UNIQUE,
    FK_ENQ_CODIGO INTEGER,
    PRIMARY KEY(PER_CODIGO),
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESPOSTAS(
	RES_CODIGO INTEGER AUTO_INCREMENT,
    RES_DESCRICAO VARCHAR(300) UNIQUE NOT NULL,
    RES_CERTA VARCHAR(1) NOT NULL,
    FK_PER_CODIGO INTEGER,
    PRIMARY KEY (RES_CODIGO),
    FOREIGN KEY (FK_PER_CODIGO) REFERENCES PERGUNTAS(PER_CODIGO) ON DELETE CASCADE
);

INSERT INTO USUARIO(USU_DATA_CADASTRO, USU_LOGIN, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE,USU_EMAIL,USU_SENHA,USU_NOME)
VALUES ("2025-10-01","LOGINLOGIN","2009-03-25","SOLTEIRO","MG","FUNDAMENTAL","EMAILEMAIL@GMAIL.COM","SENHAIDIOTA","FULANO");

INSERT INTO USUARIO(USU_DATA_CADASTRO, USU_LOGIN, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE,USU_EMAIL,USU_SENHA,USU_NOME)
VALUES ("2025-02-02","LOGINDOIS","2008-11-8","VIÚVO","PI","MÉDIO","EMAIL@OUTLOOK.COM","SENHASENHA","PESSOA");

INSERT INTO USUARIO(USU_DATA_CADASTRO, USU_LOGIN, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE,USU_EMAIL,USU_SENHA,USU_NOME)
VALUES ("2025-08-06","LOGINTREIS","2021-09-04","CASADO","BA","FUNDAMENTAL","MELIBERTEDEMIURGO@SOS.COM","ANGRYINCH","SOCORRO");

SELECT * FROM USUARIO;

INSERT INTO ENQUETE(ENQ_DATA_INICIAL,ENQ_DESCRICAO,ENQ_NOME)
VALUES ("2025-06-03","CLIQUE DUAS VEZES PARA INSERIR TEXTO","INSERIR TÍTULO");

INSERT INTO ENQUETE(ENQ_DATA_INICIAL,ENQ_DESCRICAO,ENQ_NOME)
VALUES("2024-08-10","MATE CHARLIE KIRK E REENCARNE COMO UMA FLOR DE LÓTUS","ESTADUNIDENSE SÓ SABE RESOLVER NO TIRO");

INSERT INTO ENQUETE(ENQ_DATA_INICIAL,ENQ_DESCRICAO,ENQ_NOME)
VALUES("2025-01-30","LIBERTE-SE DAS AMARRAS DO PLANO MATERIAL","ALELUIA! NÃO SE PRENDA! TRANCENDA!!!");

SELECT * FROM ENQUETE;

INSERT INTO USUARIO_RESPONDE_ENQUETE(FK_USU_CODIGO,FK_ENQ_CODIGO,URE_DATA)
VALUES("1","1","2025-10-01");

INSERT INTO USUARIO_RESPONDE_ENQUETE(FK_USU_CODIGO,FK_ENQ_CODIGO,URE_DATA)
VALUES("2","2","2025-10-01");

INSERT INTO USUARIO_RESPONDE_ENQUETE(FK_USU_CODIGO,FK_ENQ_CODIGO,URE_DATA)
VALUES("3","3","2025-10-01");

SELECT * FROM USUARIO_RESPONDE_ENQUETE;

INSERT INTO PERGUNTAS(PER_DESCRICAO,FK_ENQ_CODIGO)
VALUES ("INSERIR TEXTO","1");

INSERT INTO PERGUNTAS(PER_DESCRICAO,FK_ENQ_CODIGO)
VALUES ("QUAL FIGURA DE PODER IREMOS BALEAR HOJE??? VEJA NO PRÓXIMO EPISÓDIO!!!","2");

INSERT INTO PERGUNTAS(PER_DESCRICAO,FK_ENQ_CODIGO)
VALUES("WE DRIFT LIKE WORRIED FIRE/THE SAD MAFIOSO","3");



INSERT INTO RESPOSTAS(RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES("INSERIR DESCRIÇÃO","A","1");

INSERT INTO RESPOSTAS(RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES("QUAL GUERRA OS EUA VÃO FINANCIAR HOJE???","A","1");

INSERT INTO RESPOSTAS(RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES("DO YOU THINK THE END OF THE WORLD IS COMING?","A","1");



INSERT INTO RESPOSTAS(RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES ("PERGUNTAS PERGUNTAS","B","2");

INSERT INTO RESPOSTAS(RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES("SEGUNDA PERGUNTA","B","2");

INSERT INTO RESPOSTAS(RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES("TERCEIRA PERGUNTA","B","2");



INSERT INTO RESPOSTAS(RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES("A VIDA NAO TEM SENTIDO E TODOS VAMOS MORRER","C","3");

INSERT INTO RESPOSTAS(RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES("FATHER, INTO YOUR HANDS I COMMAND MY SPIRIT","C","3");

INSERT INTO RESPOSTAS(RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES("WHY HAVE YOU FORSAKEN ME?","C","3");

SELECT * FROM RESPOSTAS;