CREATE DATABASE IF NOT EXISTS BD_GERENCIAR_PROJETOS;
USE BD_GERENCIAR_PROJETOS;

CREATE TABLE IF NOT EXISTS PROJETO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    PRIORIDADE VARCHAR(6) NOT NULL,
    METODOLOGIA VARCHAR(100) NOT NULL,
    ORCAMENTO DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR(20) PRIMARY KEY,
    ENDERECO VARCHAR(200),
    DATA_ENTRADA DATE NOT NULL,
    CARGO VARCHAR(20) NOT NULL,
    QUALIFICACAO VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(9999) NOT NULL,
    DURACAO FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCI_TAREFA(
	FK_ID_TAREFA INTEGER,
    FOREIGN KEY (FK_ID_TAREFA) REFERENCES TAREFA(ID) ON DELETE CASCADE,
    FK_CPF_FUNCIONARIO VARCHAR(20),
    FOREIGN KEY (FK_CPF_FUNCIONARIO) REFERENCES FUNCIONARIO(CPF)
);