CREATE DATABASE IF NOT EXISTS BD_GESTAO_ESTOQUE;
USE BD_GESTAO_ESTOQUE;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    QTD INTEGER,
    DESCRICAO VARCHAR(255) NOT NULL,
    NOME VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(300) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    VALIDADE DATE,
    CUSTO DOUBLE NOT NULL,
    QTD INTEGER,
    DESCRICAO VARCHAR(300) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    FOTO BLOB NOT NULL,
    FK_ID_CATEG INTEGER,
    FOREIGN KEY (FK_ID_CATEG) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PROD_FORNE(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_PROD INTEGER,
    FOREIGN KEY (FK_ID_PROD) REFERENCES PRODUTO(ID) ON DELETE CASCADE,
    FK_CNPJ_FORNE VARCHAR(20),
    FOREIGN KEY (FK_CNPJ_FORNE) REFERENCES FORNECEDOR(CNPJ)
);