CREATE DATABASE IF NOT EXISTS BD_RES_HOTEL;
USE BD_RES_HOTEL;

CREATE TABLE IF NOT EXISTS HOTEL(
	CNPJ VARCHAR(30) PRIMARY KEY,
    EMAIL VARCHAR(300) NOT NULL,
    TELEFONE VARCHAR(30) NOT NULL,
    ENDERECO VARCHAR(300) NOT NULL,
    FOTO BLOB NOT NULL,
    AVALIACAO INTEGER
);

CREATE TABLE IF NOT EXISTS HOSPEDE(
	CPF VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(300) NOT NULL,
    TELEFONE VARCHAR(30) NOT NULL,
    ENDERECO VARCHAR(300)
);

CREATE TABLE IF NOT EXISTS QUARTO(
    NUM INTEGER PRIMARY KEY,
    FOTO BLOB NOT NULL,
    VALOR DOUBLE NOT NULL,
    DESCRICAO VARCHAR(300) NOT NULL,
    FK_CNPJ_HOTEL VARCHAR(30),
    FOREIGN KEY (FK_CNPJ_HOTEL) REFERENCES HOTEL(CNPJ) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUAR_HOS(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_NUM_QUARTO INTEGER,
    FOREIGN KEY (FK_NUM_QUARTO) REFERENCES QUARTO(NUM) ON DELETE CASCADE,
    FK_CPF_HOSPEDE VARCHAR(20),
    FOREIGN KEY (FK_CPF_HOSPEDE) REFERENCES HOSPEDE(CPF) ON DELETE CASCADE
);