CREATE DATABASE IF NOT EXISTS BD_RESERVAS_AEREAS;
USE BD_RESERVAS_AEREAS;

CREATE TABLE IF NOT EXISTS VOO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESTINO VARCHAR(150) NOT NULL,
    ORIGEM VARCHAR(150) NOT NULL,
    DURACAO FLOAT NOT NULL,
    DATA_VOO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF VARCHAR(20) PRIMARY KEY,
    TELEFONE VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(300) NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    ENDERECO VARCHAR(200) NOT NULL,
    PASSAPORTE VARCHAR(399) NOT NULL,
    IDADE INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSENTO(
	NUM_ASS INTEGER NOT NULL PRIMARY KEY,
    FILEIRA INTEGER NOT NULL,
    CUSTO DOUBLE NOT NULL,
    FK_CPF_PASS VARCHAR(20),
    FOREIGN KEY (FK_CPF_PASS) REFERENCES PASSAGEIRO(CPF) ON DELETE CASCADE,
    FK_ID_VOO INTEGER,
    FOREIGN KEY (FK_ID_VOO) REFERENCES VOO(ID) ON DELETE CASCADE
);