CREATE DATABASE IF NOT EXISTS BD_STREAMING_VIDEO;
USE BD_STREAMING_VIDEO;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(300) NOT NULL,
    PAGINA VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS VIDEO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ENDERECO VARCHAR(300) NOT NULL,
    DATA_PUBL DATE NOT NULL,
    DESCRICAO VARCHAR (999),
    FK_ID_CATEG INTEGER,
    FOREIGN KEY (FK_ID_CATEG) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VISUALICACAO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_VIDEO INTEGER,
    FOREIGN KEY (FK_ID_VIDEO) REFERENCES VIDEO(ID) ON DELETE CASCADE
);