CREATE DATABASE IF NOT EXISTS BD_ALUGUEL_PRODUTOS;
USE BD_ALUGUEL_PRODUTOS;

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLIENTE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
    );

CREATE TABLE IF NOT EXISTS PRODUTO(
	PRODUTO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(500) NOT NULL,
    PRECO DECIMAL NOT NULL,
    QTD_DISPONIVEL INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUGUEL(
	ALUGUEL_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_ALUGUEL DATE NOT NULL,
    DATA_DEVOLUCAO DATE NOT NULL,
    VALOR_TOTAL DECIMAL NOT NULL,
    FK_CLIENTE_ID INTEGER NOT NULL,
    FK_PRODUTO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID) ON DELETE CASCADE
);


-- DML - LINGUAGEM DE MANIPULACAO
-- INSERT - INSERIR
INSERT INTO CLIENTE (EMAIL,TELEFONE,CPF,NOME)
VALUES("email@hotmail.com","19993456789","12312312312","Fulano");

INSERT INTO CLIENTE (EMAIL,TELEFONE,CPF,NOME)
VALUES("fernanamnogueira26@gmail.com","19993864710","48595297827","FMN");

INSERT INTO CLIENTE (NOME,EMAIL,TELEFONE,CPF)
VALUES("Fulana","emaiou@gmail.com","17771234567","98787676554");

-- SELECT - SELECIONAR
SELECT * FROM CLIENTE;

-- INSERIR PRODUTOS
INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("MacBook M4","Notebook Apple",4789.90,5);

SELECT * FROM PRODUTO;

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Celta tunado","Carro do modelo Celta customizado",20000,1);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Pão Pullman","Pão de forma",13.60,50);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Caminhão pipa tunado","Caminhão pipa aprimorado","150000",2);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Makita","Serra mármore marca Makita",231,30);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Chevette 94","Chevette caramelo sem carburador",10450,3);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Jazz","Action Figure Jazz Transformers G1","105",24);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Kombi","Kombi 96",3000,0);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Ars Goetia","Livro",200,78);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Torneira","Torneira de soco inglês",150,1234567);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Abridor de coco","Abridor de coco",8.50,1);

-- INSERIR ALUGUEIS
SELECT * FROM CLIENTE;
SELECT * FROM PRODUTO;

-- ATUALIZAR UM REGISTRO (UPDATE)
UPDATE PRODUTO
SET PRECO = 3500
WHERE PRODUTO_ID = 1;

-- 3 PRECO PRODUTO UPDATE
UPDATE PRODUTO
SET PRECO = 450
WHERE PRODUTO_ID = 7;

UPDATE PRODUTO
SET PRECO = 666
WHERE PRODUTO_ID = 9;

UPDATE PRODUTO
SET PRECO = 50000
WHERE PRODUTO_ID = 2;

-- 5 QTD DISPONIVEL PRODUTO UPDATE
UPDATE PRODUTO
SET QTD_DISPONIVEL = 95
WHERE PRODUTO_ID = 2;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 4
WHERE PRODUTO_ID = 1;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 25
WHERE PRODUTO_ID = 5;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 46
WHERE PRODUTO_ID = 10;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 20
WHERE PRODUTO_ID = 4;

-- 2 EMAIL CLIENTE UPDATE
UPDATE CLIENTE
SET EMAIL = "NEWBLUEPRINT@OUTLOOK.COM"
WHERE CLIENTE_ID = 1;

UPDATE CLIENTE
SET EMAIL = "MARIALUIZA@GMAIL.COM"
WHERE CLIENTE_ID = 4;

-- 8 DATA DEVOLUCAO ALUGUEL UPDATE
UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2026-07-09"
WHERE ALUGUEL_ID = 1;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2030-06-05"
WHERE ALUGUEL_ID = 2;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2027-03-25"
WHERE ALUGUEL_ID = 3;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2030-12-06"
WHERE ALUGUEL_ID = 4;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2028-03-04"
WHERE ALUGUEL_ID = 5;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2031-08-20"
WHERE ALUGUEL_ID = 6;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2028-06-04"
WHERE ALUGUEL_ID = 7;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2049-11-10"
WHERE ALUGUEL_ID = 8;



SELECT * FROM ALUGUEL;

INSERT ALUGUEL (DATA_ALUGUEL,
				DATA_DEVOLUCAO,
                VALOR_TOTAL,
                FK_CLIENTE_ID,
                FK_PRODUTO_ID)
VALUES ("2025-09-24",
		"2025-10-01",
        300,
        4,
        5);
-- 1
INSERT ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01",17,3,3);
-- 2
INSERT ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01",180,3,7);
-- 3
INSERT ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01",210,1,9);
-- 4
INSERT ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-09-25",13,4,11);
-- 5
INSERT ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-09-25",160,4,10);
-- 6
INSERT ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-10-01","2025-10-08",5000,2,1);
-- 7
INSERT ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-09-28",3500,3,8);
-- 8
INSERT ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-13","2025-09-18",210,4,9);
-- 9
INSERT ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-13","2025-09-15",200000,4,4);
-- 10
INSERT ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01",12000,3,6);
-- 11
INSERT ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-08-13","2025-09-17",130,1,7);
-- 12
INSERT ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-09","2025-10-29",500,4,8);
-- 13
INSERT ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-03-20","2025-11-8",280,2,9);
-- 14
-- 15
-- 16
-- 17
-- 18
-- 19
-- 20

-- DELETE
DELETE FROM CLIENTE
WHERE CLIENTE_ID = 1;

DELETE FROM PRODUTO
WHERE PRODUTO_ID = 1;

DELETE FROM ALUGUEL
WHERE ALUGUEL_ID = 2;

SELECT *
FROM CLIENTE
WHERE CLIENTE_ID = 4;

SELECT NOME,PRECO
FROM PRODUTO
WHERE PRODUTO_ID = 3;